### ISSUE TITLE
Case to port to iproute?

### ISSUE THREAD

**Issue by ghenry** [librestack/librecast#15]
https://github.com/ebiken/doc-network/wiki/Linux-iproute2-:-Adding-bridge-(ip-link-add)

https://wiki.linuxfoundation.org/networking/bridge
https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/bridge-utils.git
https://wiki.linuxfoundation.org/networking/iproute2

**Comment by brettsheffield** [comment]
iproute2 has no public API we can use.  It is a command-line tool.

So is bridge-utils, but the difference is it has a really nice internal library, libbridge which does exactly what we need.  I turned this into a shared library: 

 - https://github.com/brettsheffield/bridge-utils

I contacted upstream who have no interest in maintaining it, so I do.

iproute2 is not a suitable or complete replacement for bridge-utils. The output is less readable, the commands are longer and more complicated to type, and the functionality of bridge-utils has not been duplicated in iproute2.

Internally (as your first link shows), iproute2 uses the kernel's netlink API, which is an unholy mess:
 - https://github.com/ebiken/doc-network/wiki/Linux-iproute2-:-Adding-bridge-(ip-link-add)

Take a look at the digging he's had to do through iproute2's internals to figure out the special incantations and magic numbers needed to just add a bridge.  Yikes.

I can't really see any advantage in porting to netlink at the moment.

**Comment by ghenry** [comment]
Ah, I missed your lib, was trying to find libbridge.h on my Fedora 31 system and that led me down this path.

Maybe this should be a bug report to update the INSTALL guide with a link to your lib?

**Comment by brettsheffield** [comment]
INSTALL already links to my library, with instructions on how to install it...

**Comment by ghenry** [comment]
Oh yeah, it does now :-)
