### ISSUE TITLE
Respect LDFLAGS and CPPFLAGS for hardening flags

### ISSUE THREAD

**Issue by vagrantc** [librestack/librecast#35]
If you add LDFLAGS and CPPFLAGS support, the Debian package builds will have some hardening features enabled:

https://lintian.debian.org/tags/hardening-no-fortify-functions.html
https://lintian.debian.org/tags/hardening-no-bindnow.html

**Comment by brettsheffield** [comment]
@vagrantc I believe my latest commit resolves this issue. Let me know if it does not.
